#
# https://github.com/P3TERX/Actions-OpenWrt
#
# File: .github/workflows/openwrt-bulder.yml
# Description: Build OpenWrt using GitHub Actions
#
# Copyright (c) 2019-2024 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# REPO_TAG: 20230609
# git clone $REPO_URL -b $REPO_TAG openwrt
#
# REPO_BRANCH: master
# git clone $REPO_URL -b $REPO_BRANCH openwrt
#

name: openwrt-builder-hc5962

on:
  repository_dispatch:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master 
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: hc5962.config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: false
  TZ: Asia/Shanghai

# 剩下的代码保持不变
